### ISSUE TITLE
why it is empty now

### ISSUE THREAD

**Issue by Joanna1212** [ChienYuLu/Play-As-You-Like-Timbre-Enhanced-Multi-modal-Music-Style-Transfer#1]
I read your paper. I am very interested in this, I want to see your code and demo

**Comment by ssrp** [comment]
Same here.

**Comment by ChienYuLu** [comment]
Sorry for the late release.

**Comment by ssrp** [comment]
Hi @ChienYuLu, thank you very much for the prompt response and the documented code!
Could you please provide a pre-trained PyTorch model (perhaps the best one) which we could use to skip the training time? 
Thank you! :)
