### ISSUE TITLE
Trained checkpoint

### ISSUE THREAD

**Issue by tartarleft** [ChienYuLu/Play-As-You-Like-Timbre-Enhanced-Multi-modal-Music-Style-Transfer#2]
Hi, I'm interested in your work and want to run the model on the test samples, can you provide the trained checkpoint of the model? Thank you!

**Comment by snoopyisadog** [comment]
Hi, we provide only the YouTube links to the data we used in the experiments:
    Playlist of Guitar solos: https://goo.gl/zZv9SS
    Playlist of Piano solos: https://goo.gl/VbA2rA
